### ISSUE TITLE
Audio and Playback Issue

### ISSUE THREAD

**Issue by perusudroid** [arthur3486/ARVI#2]
Hi, 
Your library found to be awesome but i faced some issues like no audio for video files and no playback option like seekbar and forward. Does your library support all these or still under construction?.

**Comment by arthur3486** [comment]
Hi @perusudroid the library does indeed support the audio management, as well as Player controls.

In the demo app the audio is disabled for each corresponding Item ViewHolder (See [`VideoItemViewHolder`](https://github.com/arthur3486/ARVI/blob/master/sample/src/main/java/com/arthurivanets/sample/adapters/adapster/VideoItemViewHolder.kt#L106), but that doesn't mean that you can't enable it, in fact you can adjust basically any playback-related property exposed by the [`Playable`](https://github.com/arthur3486/ARVI/blob/master/arvi/src/main/java/com/arthurivanets/arvi/widget/Playable.java) contract.

Also, regarding the Player controls, here you have several options, the first one is the default [`PlayerView`](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/ui/PlayerView.html) controls provided by the ExoPlayer (see the corresponding API [documentation](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer2/ui/PlayerView.html)), the second one is the custom implementation of the controls with all the corresponding event handling and manual management of the playback (here, once again you would have to look into the API exposed to you via the [`Playable`](https://github.com/arthur3486/ARVI/blob/master/arvi/src/main/java/com/arthurivanets/arvi/widget/Playable.java) contract).

Hope this helped to clarify the things! :)
